hyprwm/hyprpaper

Makefile

Believe makefile requires tabs over spaces, fixes the error "Makefile:48: *** missing separator.  Stop." when trying to run make command

Fixes spacing issue in Makefile

---

nix/default.nix

nix has recently renamed `utillinux` to `util-linux`, so the scripted needed to be updated for this

fix: fix issue with util-linux rename on nix

---

src/Hyprpaper.hpp
src/config/ConfigManager.cpp
src/main.cpp

Provides config file path overriding in same fashion hyprland currently does (through `--config|-c`).
Should be consistent with hyprland codebase's implementation. Tested.

feat: Provide way to override default config file path

---

src/config/ConfigManager.cpp

The following config file may disturb a user (me in the present situation).
```
preload=/home/vincent/Downloads/steampunk.jpg
greload=/home/vincent/Downloads/evangelion.jpg
wallpaper=HDMI-A-1,/home/vincent/Downloads/evangelion.jpg
wallpaper=DVI-D-1,/home/vincent/Downloads/steampunk.jpg
```
The only error that hyprpaper will output is that it couldn't set the wallpaper "evangelion.jpg" as it wasn't preloaded. However, one would have preferred having the direct error "`greload` isn't a valid keyword" instead.
So in this pull request, we error out after the first occuring error.
Moreover, some part of the code made little sense and were corrected. First of all, the try/catch was suppressed as there is not throw instruction. Then `parseError.find("Config error at line") != 0` is always false …

Fixing config manager that doesn't error out on bad keyword.

---

src/config/ConfigManager.cpp

Problem if config had:
`wallpaper = DP-1,contain:~/Pictures/bg.jpg`
Config was not parsing '~' to the HOME directory.
Fixed by changing the order of parsing out the 'contain:' keyword out before parsing path for bg.

Allow parsing home dir with contains keyword

---

src/Hyprpaper.cpp

```
/ix/build/t0VbWw3Gs81M6qL1/src/src/Hyprpaper.cpp:203:38: error: reference to local binding 'wt' declared in enclosing function 'CHyprpaper::ensurePoolBuffersPresent'
return el->target == wt.m_szPath && el->pixelSize == m->size * m->scale;
^
/ix/build/t0VbWw3Gs81M6qL1/src/src/Hyprpaper.cpp:196:23: note: 'wt' declared here
for (auto& [file, wt] : m_mWallpaperTargets) {
```

Update Hyprpaper.cpp, fix clang++ build

---

src/Hyprpaper.cpp

Capture wt by reference, thus fixing https://github.com/hyprwm/hyprpaper/pull/31#issuecomment-1372228788
I can not reproduce asserts from linked PR, but I think that now I fully reproduce [&] behaviour.
```
/ix/build/t0VbWw3Gs81M6qL1/src/src/Hyprpaper.cpp:203:38: error: reference to local binding 'wt' declared in enclosing function 'CHyprpaper::ensurePoolBuffersPresent'
return el->target == wt.m_szPath && el->pixelSize == m->size * m->scale;
^
/ix/build/t0VbWw3Gs81M6qL1/src/src/Hyprpaper.cpp:196:23: note: 'wt' declared here
for (auto& [file, wt] : m_mWallpaperTargets) {
```

Fix clang build, second version

---

CMakeLists.txt

Using `-std=c++2b` instead of `-std=c++23` allows compilation with clang instead of gcc.
(This also works with gcc of course)

Fix compilation with clang

---

CMakeLists.txt
nix/default.nix
src/render/WallpaperTarget.cpp

Related to: #52 #55
I did my best to implement filetype detection using libmagic. This should be available in most distributions.
TODO:

[RFC] Filetype detection without extension

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp

The default config path will now first check if XDG_CONFIG_HOME exists and will use it rather than `$HOME/.config` if it does exist.

Added support for XDG_CONFIG_HOME

---

src/Hyprpaper.cpp

Check if the file is a symlink and use the real path instead.

Support for symlinks

---

src/Hyprpaper.cpp

Fixes issue #74
The `clearWallpaperFromMonitor` function clears most properties of the `SMonitor` struct to prepare for reloading its wallpaper. However, if no initial wallpaper was loaded by the config file the `hasATarget` flag would be stuck to false, blocking IPC commands from updating its wallpaper.
This fixes the issue by setting the flag back to its default value in `clearWallpaperFromMonitor`.

Reset hasATarget when issuing wallpaper command

---

src/Hyprpaper.cpp

Currently, hyprpaper assumes absolute paths in symlinks. This converts the symlink target to its absolute path before loading.

fix: Read absolute path of symlinks

---

src/Hyprpaper.cpp

It's related to:
https://github.com/hyprwm/Hyprland/issues/3523
I moved ``scale`` to a double because from what I've seen it sometimes prevented single lines of pixels poking from behind but just that isn't enough to completely resolve the issue. Only sensible way I found was to just draw a black background first and then draw the wallpaper.
Also rearranged the if statement a little to reduce code repetition.

Always draw a black background behind the wallpaper

---

src/ipc/Socket.cpp

The previous implementation was closing the connection right after 1 message (ligne 87) so i couldn't send multiple request with the same socket, this fix it.

Allow multiple read from IPC + some refactor

---

Makefile

I changed the default to `/usr` since the install step was using that anyway.

fix: respect PREFIX in Makefile

---

flake.lock
nix/default.nix

At the moment, the hyprpaper build is failing with the following error:
```
In file included from /build/x9p86pbqbvwry48qacajgfyk8zd2sxir-source/src/render/../defines.hpp:3,
from /build/x9p86pbqbvwry48qacajgfyk8zd2sxir-source/src/render/LayerSurface.hpp:3,
from /build/x9p86pbqbvwry48qacajgfyk8zd2sxir-source/src/render/LayerSurface.cpp:1:
/build/x9p86pbqbvwry48qacajgfyk8zd2sxir-source/src/render/../includes.hpp:30:10: fatal error: GLES3/gl32.h: No such file or directory
30 | #include <GLES3/gl32.h>
|          ^~~~~~~~~~~~~~
compilation terminated.
```
Fixed the problem by adding libGL to buildInputs. Also updated flake.lock to the latest nixos-23.11.

Fix nix build, update flake.lock

---

flake.lock
flake.nix
nix/default.nix

Nix: add hyprlang

---

README.md
src/ipc/Socket.cpp

Added commands to be able to get the state of hyprpaper to make it easier to do dynamic loading and unloading of wallpapers.
Example usage:
```
$ hyprctl hyprpaper listactive
eDP-1 = /home/username/Pictures/wallpaper/A.png
HDMI-A-1 = /home/username/Pictures/wallpaper/B.png
$ hyprctl hyprpaper listloaded
/home/username/Pictures/wallpaper/A.png
/home/username/Pictures/wallpaper/B.png
/home/username/Pictures/wallpaper/C.png
```
My code is a little janky, so if you want me to change it or move it somewhere. I'd be happy to.

ipc: Added listloaded and listactive requests

---

README.md
src/config/ConfigManager.cpp

In response to #138
Fixes being able to assign a wallpaper to a nonexistent monitor by throwing an error if the monitor doesn't exist.
Clarified README to the specifics of the handleWallpaper function.
Without really modifying the existing logic for the `if (MONITOR.empty()) {` part there isn't a neat way of just assigning a wallpaper to all screens at once.
This does fix the issue aswell as follows:
```sh
$ hyprctl hyprpaper listactive
eDP-1 = <wp1>
HDMI-A-1 = <wp2>
$ hyprctl hyprpaper preload <wp3>
ok
$ hyprctl hyprpaper wallpaper ", <wp3>"
ok
$ hyprctl hyprpaper listactive
eDP-1 = <wp1>
HDMI-A-1 = <wp2>
$ hyprctl hyprpaper wallpaper "ramd, <wp3>"
wallpaper failed (no such monitor)
$ hyprctl hyprpaper listactive
eDP-1 = <wp1>
HDMI-A-1 = <wp2>
```

Fix error checking while changing wallpaper.

---

README.md

A small edit to the readme that links the user to the proper page for the arch package. The old link was outdated as the package has been moved from the community repo to the extra repo.

Updated link to reflect arch package movement from community to extra

---

flake.nix
nix/hm-module.nix

This PR adds the home-manager module for `hyprpaper`.
I have taken a big inspiration from the `hyprlock` and `hypridle` modules.
In terms of design, I don't know if the `preloads` and `wallpapers` option should be in plural form (rather than simply `preload` and `wallpaper`).
cc @fufexan

Nix: add home-manager module

---

CMakeLists.txt

Using `add_compile_options(-std=c++2b)` passes the flag to C compiler aswell. gcc ignores it but clang fails compilation with the error: `invalid argument '-std=c++2b' not allowed with 'C'`.
Using `set(CMAKE_CXX_STANDARD 23)` fixes that.

Set standard exclusively for c++

---

README.md

As commented in #161, the `hyprlang-devel` package was missing in the Fedora instructions.
After installing the dependency it compiles and installs without any errors

Added missing hyprlang-devel dependency for Fedora

---

src/events/Events.cpp

This change aligns the behavior of using desc to target monitors in hyprpaper with that in [hyprland](https://github.com/hyprwm/Hyprland/blob/b1a94302897ae559c877471f7d365651bcd24ad4/src/helpers/Monitor.cpp#L58).

Remove comma from monitor description

---

nix/hm-module.nix

Fix typo in hm-module.nix

---

src/helpers/Bmp.cpp
src/helpers/Bmp.hpp
src/render/WallpaperTarget.cpp
src/render/WallpaperTarget.hpp

Added a new function to create a cairo surface from a bitmap image (.bmp)

Bitmap image support

---

src/config/ConfigManager.cpp

The current implementation produces coredump due to unhandled exception if the process does not have permission to access files specified in arguments of std::filesystem::exists.

config: produce error instead fs::exists exceptions

---

CMakeLists.txt

This would fix a cross-compile issue where hyprwayland-scanner is pulled in for target but needs to run on host.

CMakeLists: require native hyprwayland-scanner

---

CMakeLists.txt
flake.lock
nix/default.nix

This is required to build on NixOS after https://github.com/NixOS/nixpkgs/pull/214906 (which is already in nixos-unstable-small).

CMakeLists: look for wayland.xml protocol in wayland-scanner pkgdata

---

src/helpers/Monitor.cpp
src/helpers/Monitor.hpp

very simple change; ready to be merged whenever.
https://github.com/user-attachments/assets/9f130db0-2de6-47a5-ae62-5eef33b412b8

implement wl_output_transform

---

CMakeLists.txt

Install the service file to the proper location. This mirrors [hypridle](https://github.com/hyprwm/hypridle/blob/9d97c2288316f7ed474c0d8cd248516d8fb72037/CMakeLists.txt#L99-L100), [xdg-desktop-portal-hyprland](https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/e09dfe2726c8008f983e45a0aa1a3b7416aaeb8a/CMakeLists.txt#L147-L149) and [hyprpolkitagent](https://github.com/hyprwm/hyprpolkitagent/blob/3bef8bf8fcac95339d1e8cab3addbe83a7f99d57/CMakeLists.txt#L57-L58)

Move systemd service install

---

src/config/ConfigManager.cpp

hyprpaper will throw an exception if a user does not have a config file in any of the default directories. Interestingly I noticed it will run when using the `--config` flag even if that points to a file that does not exist:
```
[hyprpaper]$ ./build/hyprpaper
[LOG] Welcome to hyprpaper!
built from commit 79e0992927d8d8335e8c727461d35b0c73a855bf (    nix: update flake.lock (252))
terminate called after throwing an instance of 'std::runtime_error'
what():  Could not find config in HOME, XDG_CONFIG_HOME, XDG_CONFIG_DIRS or /etc/hypr.
Aborted (core dumped)
[hyprpaper]$ ls /tmp/foo
ls: cannot access '/tmp/foo': No such file or directory
[hyprpaper]$ ./build/hyprpaper --config /tmp/foo
[LOG] Welcome to hyprpaper!
built from commit 79e0992927d8d8335e8c727461d35b0c73a855bf (    nix: update …
```

Return empty string instead of throwing if unable to find default config

---

src/config/ConfigManager.cpp
src/config/ConfigManager.hpp

Hi, short answer: I'm creating a Wallpaper Manager in Rust (rs-paper name pending*) and as part of my logic for saving wallpaper "sets", I need to be able to quickly adjust per-display wallpapers without altering other monitors. I've come up with the solution of having .conf files for each display (auto-created by parsing hyprctl -j monitor results) and my app will take a selected wallpaper and update the specific .conf file to that wallpaper.
Using $variables, I can have a file be DP-1.conf and echo into it $DP-1 = path/to/image.png
Now my hyprpaper.conf can read:
preload = $DP-1
wallpaper = DP-1, $DP-1
I never adjust hyprpaper.conf outside of initial setup (which runs on start-up for simplicity) and my logic only targets per-monitor .conf files instead of re-writing the entire …

Added "source=" capability to Hyprpaper .conf file

---

CMakeLists.txt

**Using these build commands found on the main page of the repo:**
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprpaper -jnproc 2>/dev/null || getconf _NPROCESSORS_CONF
**I caused this error when building:**
/home/blake-sama/Developer/hyprpaper/src/main.cpp: In function ‘int main(int, char**, char**)’:
: error: unable to find string literal operator ‘operator""source’ with ‘const char [19]’, ‘long unsigned int’ arguments
/home/blake-sama/Developer/hyprpaper/src/main.cpp:6:90: note: in expansion of macro ‘GIT_COMMIT_MESSAGE’
6 | Debug::log(LOG, "Welcome to hyprpaper!\nbuilt from commit {} ({})", GIT_COMMIT_HASH, GIT_COMMIT_MESSAGE);
| ^~~~~~~~~~~~~~~~~~
make[3]: *** …

Build error occurred; commits with "" break build commands.
